
const String LOAD = "درحال بارگزاری ...";
const String SEND = "ارسال";
const String CANCEL = "انصراف";
const String RECONNECT = "تلاش دوباره";
const String CONNECTION_PROBLEM = "مشکل در اتصال";
const String CONNECTION_PROBLEM_COMMENT = "اتصال اینترنت را بررسی کنید. در صورتی که از اتصال اینترنت اطمینان دارید لطفا صبر کنید ";
const String SEND_SMS = "شماره تلفن همراه خود را برای ارسال پیامک ورود وارد کنید";
const String PHONE_NUMBER = "شماره تماس";
const String PHONE_NUMBER_ERROR = "شماره تماس را صحیح وارد کنید";
const String SEND_SMS_VERIFY = "کد تایید برای شماره %s ارسال شود ؟";
const String SECURITYSTAMP = "کد امنیتی";
const String SECURITYSTAMP_ERROR = "کد امنیتی را صحیح وارد کنید";
const String SEND_SECURITYSTAMP = "کد امنیتی را وارد کنید";
const String SELECT_IMG = "انتخاب تصویر";
const String SELECT_IMG_ERROR1 = "این فرمت پشتیبانی نمیشود.  فرمت پشتیبانی شده jpg,jpeg";
const String SELECT_IMG_ERROR2 = "حجم تصویر زیاد است. حداکثر حجم فایل 5 مگابایت";
const String SELECT_IMG_COMMENT = "یک تصویر انتخاب کنید. فرمت پشتیبانی شده jpg,jpeg";
const String UPLOAD_IMG = "بارگزاری تصویر";
